"""Add Beeline integration fields to Tenant model

Revision ID: 1973a702520a
Revises: aadd29458397
Create Date: 2025-11-20 16:11:58.210514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1973a702520a'
down_revision: Union[str, None] = 'aadd29458397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type_id', sa.Integer(), nullable=False),
    sa.Column('grantee_user_id', sa.Integer(), nullable=False),
    sa.Column('grantor_user_id', sa.Integer(), nullable=False),
    sa.Column('permission_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['entity_type_id'], ['entity_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grantee_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grantor_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type_id', 'grantee_user_id', name='_entity_grantee_uc')
    )
    with op.batch_alter_table('shared_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shared_access_entity_type_id'), ['entity_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shared_access_grantee_user_id'), ['grantee_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shared_access_grantor_user_id'), ['grantor_user_id'], unique=False)

    op.create_table('calendar_view_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('entity_type_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('title_attribute_id', sa.Integer(), nullable=False),
    sa.Column('start_date_attribute_id', sa.Integer(), nullable=False),
    sa.Column('end_date_attribute_id', sa.Integer(), nullable=True),
    sa.Column('is_allday_attribute_id', sa.Integer(), nullable=True),
    sa.Column('color_attribute_id', sa.Integer(), nullable=True),
    sa.Column('color_settings', sa.Text(), nullable=True),
    sa.Column('filters', sa.Text(), nullable=True),
    sa.Column('visible_fields', sa.Text(), nullable=True),
    sa.Column('default_view', sa.String(length=20), nullable=False),
    sa.Column('hide_weekends', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['color_attribute_id'], ['attributes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['end_date_attribute_id'], ['attributes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entity_type_id'], ['entity_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['is_allday_attribute_id'], ['attributes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['start_date_attribute_id'], ['attributes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['title_attribute_id'], ['attributes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_view_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_view_configs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('attribute_value_many_to_many_links',
    sa.Column('attribute_value_id', sa.Integer(), nullable=False),
    sa.Column('target_entity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_value_id'], ['attribute_values.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attribute_value_id', 'target_entity_id')
    )
    op.create_table('celery_crontab_schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('minute', sa.String(length=240), nullable=True),
    sa.Column('hour', sa.String(length=96), nullable=True),
    sa.Column('day_of_week', sa.String(length=64), nullable=True),
    sa.Column('day_of_month', sa.String(length=124), nullable=True),
    sa.Column('month_of_year', sa.String(length=64), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('celery_interval_schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('every', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=24), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('celery_periodic_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('task', sa.String(length=255), nullable=True),
    sa.Column('interval_id', sa.Integer(), nullable=True),
    sa.Column('crontab_id', sa.Integer(), nullable=True),
    sa.Column('solar_id', sa.Integer(), nullable=True),
    sa.Column('args', sa.Text(), nullable=True),
    sa.Column('kwargs', sa.Text(), nullable=True),
    sa.Column('queue', sa.String(length=255), nullable=True),
    sa.Column('exchange', sa.String(length=255), nullable=True),
    sa.Column('routing_key', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('one_off', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_run_count', sa.Integer(), nullable=False),
    sa.Column('date_changed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sqlite_autoincrement=True
    )
    op.create_table('celery_periodic_task_changed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('celery_solar_schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event', sa.String(length=24), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_id'))
        batch_op.drop_index(batch_op.f('ix_leads_inn'))
        batch_op.drop_index(batch_op.f('ix_leads_lead_status'))
        batch_op.drop_index(batch_op.f('ix_leads_organization_name'))
        batch_op.drop_index(batch_op.f('ix_leads_tenant_id'))

    op.drop_table('leads')
    with op.batch_alter_table('legal_entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legal_entities_id'))
        batch_op.drop_index(batch_op.f('ix_legal_entities_inn'))
        batch_op.drop_index(batch_op.f('ix_legal_entities_ogrn'))
        batch_op.drop_index(batch_op.f('ix_legal_entities_tenant_id'))

    op.drop_table('legal_entities')
    with op.batch_alter_table('individuals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_individuals_email'))
        batch_op.drop_index(batch_op.f('ix_individuals_full_name'))
        batch_op.drop_index(batch_op.f('ix_individuals_id'))
        batch_op.drop_index(batch_op.f('ix_individuals_inn'))
        batch_op.drop_index(batch_op.f('ix_individuals_tenant_id'))

    op.drop_table('individuals')
    with op.batch_alter_table('attribute_aliases', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('attribute_aliases_tenant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('attribute_values', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value_text', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_attribute_values_attribute_id'), ['attribute_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attribute_values_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attribute_values_value_boolean'), ['value_boolean'], unique=False)
        batch_op.create_index(batch_op.f('ix_attribute_values_value_date'), ['value_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attribute_values_value_float'), ['value_float'], unique=False)
        batch_op.create_index(batch_op.f('ix_attribute_values_value_integer'), ['value_integer'], unique=False)
        batch_op.create_index(batch_op.f('ix_attribute_values_value_string'), ['value_string'], unique=False)
        batch_op.create_index(batch_op.f('ix_attribute_values_value_time'), ['value_time'], unique=False)
        batch_op.drop_constraint(batch_op.f('attribute_values_entity_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'entities', ['entity_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('attributes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('back_relation_display_attribute_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reciprocal_attribute_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('allow_multiple_selection', sa.Boolean(), nullable=False))
        batch_op.drop_constraint(batch_op.f('attributes_target_entity_type_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('attributes_display_attribute_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('attributes_source_attribute_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('attributes_target_attribute_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'attributes', ['source_attribute_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'entity_types', ['target_entity_type_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'attributes', ['display_attribute_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'attributes', ['target_attribute_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'attributes', ['reciprocal_attribute_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'attributes', ['back_relation_display_attribute_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('entity_types', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('entity_types_tenant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('roles_tenant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('select_option_lists', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('select_option_lists_tenant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('table_aliases', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('table_aliases_tenant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modulbank_api_token', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('modulbank_integration_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('modulbank_last_sync', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('modulbank_last_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('modulbank_sync_schedule_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('modulbank_sync_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('modulbank_sync_weekday', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('modulbank_periodic_task_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('modulbank_sync_sources', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('beeline_api_token', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('beeline_integration_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('beeline_last_sync', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('beeline_last_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('beeline_sync_schedule_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('beeline_sync_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('beeline_sync_weekday', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('beeline_periodic_task_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(), nullable=True))
        batch_op.drop_constraint(batch_op.f('users_tenant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('users_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'])
        batch_op.drop_column('avatar_url')

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('beeline_periodic_task_id')
        batch_op.drop_column('beeline_sync_weekday')
        batch_op.drop_column('beeline_sync_time')
        batch_op.drop_column('beeline_sync_schedule_type')
        batch_op.drop_column('beeline_last_error')
        batch_op.drop_column('beeline_last_sync')
        batch_op.drop_column('beeline_integration_status')
        batch_op.drop_column('beeline_api_token')
        batch_op.drop_column('modulbank_sync_sources')
        batch_op.drop_column('modulbank_periodic_task_id')
        batch_op.drop_column('modulbank_sync_weekday')
        batch_op.drop_column('modulbank_sync_time')
        batch_op.drop_column('modulbank_sync_schedule_type')
        batch_op.drop_column('modulbank_last_error')
        batch_op.drop_column('modulbank_last_sync')
        batch_op.drop_column('modulbank_integration_status')
        batch_op.drop_column('modulbank_api_token')

    with op.batch_alter_table('table_aliases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('table_aliases_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('select_option_lists', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('select_option_lists_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('roles_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('entity_types', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('entity_types_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('attributes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('attributes_target_attribute_id_fkey'), 'attributes', ['target_attribute_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('attributes_source_attribute_id_fkey'), 'attributes', ['source_attribute_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('attributes_display_attribute_id_fkey'), 'attributes', ['display_attribute_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('attributes_target_entity_type_id_fkey'), 'entity_types', ['target_entity_type_id'], ['id'])
        batch_op.drop_column('allow_multiple_selection')
        batch_op.drop_column('reciprocal_attribute_id')
        batch_op.drop_column('back_relation_display_attribute_id')

    with op.batch_alter_table('attribute_values', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('attribute_values_entity_id_fkey'), 'entities', ['entity_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_attribute_values_value_time'))
        batch_op.drop_index(batch_op.f('ix_attribute_values_value_string'))
        batch_op.drop_index(batch_op.f('ix_attribute_values_value_integer'))
        batch_op.drop_index(batch_op.f('ix_attribute_values_value_float'))
        batch_op.drop_index(batch_op.f('ix_attribute_values_value_date'))
        batch_op.drop_index(batch_op.f('ix_attribute_values_value_boolean'))
        batch_op.drop_index(batch_op.f('ix_attribute_values_entity_id'))
        batch_op.drop_index(batch_op.f('ix_attribute_values_attribute_id'))
        batch_op.drop_column('value_text')

    with op.batch_alter_table('attribute_aliases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('attribute_aliases_tenant_id_fkey'), 'tenants', ['tenant_id'], ['id'])

    op.create_table('individuals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('inn', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_sole_proprietor', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('founder_in', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('manager_in', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('other_position', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('monitoring', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('individuals_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('individuals_pkey'))
    )
    with op.batch_alter_table('individuals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_individuals_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_individuals_inn'), ['inn'], unique=True)
        batch_op.create_index(batch_op.f('ix_individuals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_individuals_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_individuals_email'), ['email'], unique=False)

    op.create_table('legal_entities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('short_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inn', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('kpp', sa.VARCHAR(length=9), autoincrement=False, nullable=True),
    sa.Column('ogrn', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('registration_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('liquidation_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('primary_activity_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('primary_activity_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('employee_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('managers', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ex_managers', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('shareholders', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('founders', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ex_founders', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('share_details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('established_entities', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('authorized_capital', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('websites', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone_numbers', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ex_addresses', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('financial_report_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('net_profit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('enforcement_proceedings_sum', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('enforcement_proceedings_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pfr_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fss_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('foms_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('okpo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('okato', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('oktmo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('okopf', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('okogu', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('okfs', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tax_authority', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('other_info', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('legal_entities_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('legal_entities_pkey'))
    )
    with op.batch_alter_table('legal_entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legal_entities_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_entities_ogrn'), ['ogrn'], unique=True)
        batch_op.create_index(batch_op.f('ix_legal_entities_inn'), ['inn'], unique=True)
        batch_op.create_index(batch_op.f('ix_legal_entities_id'), ['id'], unique=False)

    op.create_table('leads',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('inn', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('establishment_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('contact_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('websites', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lead_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('scenario', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('responsible_manager_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('primary_activity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('okved_codes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('employee_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('manager_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('authorized_capital', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('net_profit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('predecessors', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('successors', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('monitoring', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_contact_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['responsible_manager_id'], ['users.id'], name=op.f('leads_responsible_manager_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('leads_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('leads_pkey'))
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_organization_name'), ['organization_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_lead_status'), ['lead_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_inn'), ['inn'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_id'), ['id'], unique=False)

    op.drop_table('celery_solar_schedule')
    op.drop_table('celery_periodic_task_changed')
    op.drop_table('celery_periodic_task')
    op.drop_table('celery_interval_schedule')
    op.drop_table('celery_crontab_schedule')
    op.drop_table('attribute_value_many_to_many_links')
    with op.batch_alter_table('calendar_view_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_view_configs_tenant_id'))

    op.drop_table('calendar_view_configs')
    with op.batch_alter_table('shared_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shared_access_grantor_user_id'))
        batch_op.drop_index(batch_op.f('ix_shared_access_grantee_user_id'))
        batch_op.drop_index(batch_op.f('ix_shared_access_entity_type_id'))

    op.drop_table('shared_access')
    # ### end Alembic commands ###
