"""Add composite unique constraint to entity_types

Revision ID: 4c5f9a4f77d9
Revises: 91c821260327
Create Date: 2025-07-30 12:51:23.557961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c5f9a4f77d9'
down_revision: Union[str, None] = '91c821260327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity_types', schema=None) as batch_op:
        batch_op.drop_index('ix_entity_types_name')
        batch_op.create_index(batch_op.f('ix_entity_types_name'), ['name'], unique=False)
        batch_op.create_unique_constraint('_name_tenant_uc', ['name', 'tenant_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity_types', schema=None) as batch_op:
        batch_op.drop_constraint('_name_tenant_uc', type_='unique')
        batch_op.drop_index(batch_op.f('ix_entity_types_name'))
        batch_op.create_index('ix_entity_types_name', ['name'], unique=1)

    # ### end Alembic commands ###
