"""Add cascade delete to entity_type_to_entity relationship

Revision ID: 590f28caa906
Revises: 593d0b5b25ca
Create Date: 2025-07-30 10:10:35.204311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '590f28caa906'
down_revision: Union[str, None] = '593d0b5b25ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
