"""Initial database schema

Revision ID: 593d0b5b25ca
Revises: 
Create Date: 2025-06-25 15:44:27.433197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '593d0b5b25ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('entity_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_types_name'), 'entity_types', ['name'], unique=True)
    op.create_index(op.f('ix_entity_types_tenant_id'), 'entity_types', ['tenant_id'], unique=False)
    op.create_table('individuals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('inn', sa.String(length=12), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_sole_proprietor', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('founder_in', sa.Text(), nullable=True),
    sa.Column('manager_in', sa.Text(), nullable=True),
    sa.Column('other_position', sa.Text(), nullable=True),
    sa.Column('monitoring', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_individuals_email'), 'individuals', ['email'], unique=False)
    op.create_index(op.f('ix_individuals_full_name'), 'individuals', ['full_name'], unique=False)
    op.create_index(op.f('ix_individuals_id'), 'individuals', ['id'], unique=False)
    op.create_index(op.f('ix_individuals_inn'), 'individuals', ['inn'], unique=True)
    op.create_index(op.f('ix_individuals_tenant_id'), 'individuals', ['tenant_id'], unique=False)
    op.create_table('legal_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('inn', sa.String(length=12), nullable=True),
    sa.Column('kpp', sa.String(length=9), nullable=True),
    sa.Column('ogrn', sa.String(length=15), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('liquidation_date', sa.Date(), nullable=True),
    sa.Column('primary_activity_name', sa.Text(), nullable=True),
    sa.Column('primary_activity_code', sa.String(), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('managers', sa.Text(), nullable=True),
    sa.Column('ex_managers', sa.Text(), nullable=True),
    sa.Column('shareholders', sa.Text(), nullable=True),
    sa.Column('founders', sa.Text(), nullable=True),
    sa.Column('ex_founders', sa.Text(), nullable=True),
    sa.Column('share_details', sa.Text(), nullable=True),
    sa.Column('established_entities', sa.Text(), nullable=True),
    sa.Column('authorized_capital', sa.Float(), nullable=True),
    sa.Column('websites', sa.Text(), nullable=True),
    sa.Column('phone_numbers', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('ex_addresses', sa.Text(), nullable=True),
    sa.Column('financial_report_year', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('net_profit', sa.Float(), nullable=True),
    sa.Column('enforcement_proceedings_sum', sa.Float(), nullable=True),
    sa.Column('enforcement_proceedings_count', sa.Integer(), nullable=True),
    sa.Column('pfr_number', sa.String(), nullable=True),
    sa.Column('fss_number', sa.String(), nullable=True),
    sa.Column('foms_number', sa.String(), nullable=True),
    sa.Column('okpo', sa.String(), nullable=True),
    sa.Column('okato', sa.String(), nullable=True),
    sa.Column('oktmo', sa.String(), nullable=True),
    sa.Column('okopf', sa.String(), nullable=True),
    sa.Column('okogu', sa.String(), nullable=True),
    sa.Column('okfs', sa.String(), nullable=True),
    sa.Column('tax_authority', sa.String(), nullable=True),
    sa.Column('other_info', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_entities_id'), 'legal_entities', ['id'], unique=False)
    op.create_index(op.f('ix_legal_entities_inn'), 'legal_entities', ['inn'], unique=True)
    op.create_index(op.f('ix_legal_entities_ogrn'), 'legal_entities', ['ogrn'], unique=True)
    op.create_index(op.f('ix_legal_entities_tenant_id'), 'legal_entities', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('value_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['entity_type_id'], ['entity_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entity_type_id'], ['entity_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_id'), 'entities', ['id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_name', sa.String(), nullable=True),
    sa.Column('inn', sa.String(length=12), nullable=True),
    sa.Column('establishment_date', sa.Date(), nullable=True),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('websites', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('lead_status', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('scenario', sa.String(), nullable=True),
    sa.Column('responsible_manager_id', sa.Integer(), nullable=True),
    sa.Column('company_status', sa.String(), nullable=True),
    sa.Column('primary_activity', sa.Text(), nullable=True),
    sa.Column('okved_codes', sa.Text(), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('manager_name', sa.String(), nullable=True),
    sa.Column('authorized_capital', sa.Float(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('net_profit', sa.Float(), nullable=True),
    sa.Column('predecessors', sa.Text(), nullable=True),
    sa.Column('successors', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('monitoring', sa.Boolean(), nullable=True),
    sa.Column('last_contact_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['responsible_manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_inn'), 'leads', ['inn'], unique=False)
    op.create_index(op.f('ix_leads_lead_status'), 'leads', ['lead_status'], unique=False)
    op.create_index(op.f('ix_leads_organization_name'), 'leads', ['organization_name'], unique=False)
    op.create_index(op.f('ix_leads_tenant_id'), 'leads', ['tenant_id'], unique=False)
    op.create_table('attribute_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('value_string', sa.Text(), nullable=True),
    sa.Column('value_integer', sa.Integer(), nullable=True),
    sa.Column('value_float', sa.Float(), nullable=True),
    sa.Column('value_date', sa.DateTime(), nullable=True),
    sa.Column('value_boolean', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attribute_values')
    op.drop_index(op.f('ix_leads_tenant_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_organization_name'), table_name='leads')
    op.drop_index(op.f('ix_leads_lead_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_inn'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_entities_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_table('attributes')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_legal_entities_tenant_id'), table_name='legal_entities')
    op.drop_index(op.f('ix_legal_entities_ogrn'), table_name='legal_entities')
    op.drop_index(op.f('ix_legal_entities_inn'), table_name='legal_entities')
    op.drop_index(op.f('ix_legal_entities_id'), table_name='legal_entities')
    op.drop_table('legal_entities')
    op.drop_index(op.f('ix_individuals_tenant_id'), table_name='individuals')
    op.drop_index(op.f('ix_individuals_inn'), table_name='individuals')
    op.drop_index(op.f('ix_individuals_id'), table_name='individuals')
    op.drop_index(op.f('ix_individuals_full_name'), table_name='individuals')
    op.drop_index(op.f('ix_individuals_email'), table_name='individuals')
    op.drop_table('individuals')
    op.drop_index(op.f('ix_entity_types_tenant_id'), table_name='entity_types')
    op.drop_index(op.f('ix_entity_types_name'), table_name='entity_types')
    op.drop_table('entity_types')
    op.drop_table('tenants')
    # ### end Alembic commands ###
