"""Add cascade relationship from Attribute to AttributeValue

Revision ID: 91c821260327
Revises: 542b2b14330f
Create Date: 2025-07-30 12:46:51.741594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91c821260327'
down_revision: Union[str, None] = '542b2b14330f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
