"""Add formula support to Attribute

Revision ID: a7fecfae6065
Revises: d7135c386205
Create Date: 2025-10-02 10:11:14.788819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7fecfae6065'
down_revision: Union[str, None] = 'd7135c386205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attributes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('formula_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attributes', schema=None) as batch_op:
        batch_op.drop_column('formula_text')

    # ### end Alembic commands ###
