"""Add relation fields to Attribute model

Revision ID: aadd29458397
Revises: a7fecfae6065
Create Date: 2025-10-07 09:55:47.130641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aadd29458397'
down_revision: Union[str, None] = 'a7fecfae6065'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attributes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency_symbol', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('target_entity_type_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source_attribute_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('target_attribute_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('display_attribute_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'entity_types', ['target_entity_type_id'], ['id'])
        batch_op.create_foreign_key(None, 'attributes', ['source_attribute_id'], ['id'])
        batch_op.create_foreign_key(None, 'attributes', ['display_attribute_id'], ['id'])
        batch_op.create_foreign_key(None, 'attributes', ['target_attribute_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attributes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('display_attribute_id')
        batch_op.drop_column('target_attribute_id')
        batch_op.drop_column('source_attribute_id')
        batch_op.drop_column('target_entity_type_id')
        batch_op.drop_column('currency_symbol')

    # ### end Alembic commands ###
